// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn756TUdxyRR7Gfo7bjqT-gtrU7hfyO9E',
    appId: '1:756530453252:web:4d48150ce03e4e6e614e51',
    messagingSenderId: '756530453252',
    projectId: 'hydra-bin',
    authDomain: 'hydra-bin.firebaseapp.com',
    storageBucket: 'hydra-bin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn756TUdxyRR7Gfo7bjqT-gtrU7hfyO9E',
    appId: '1:756530453252:android:4d48150ce03e4e6e614e51',
    messagingSenderId: '756530453252',
    projectId: 'hydra-bin',
    storageBucket: 'hydra-bin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn756TUdxyRR7Gfo7bjqT-gtrU7hfyO9E',
    appId: '1:756530453252:ios:4d48150ce03e4e6e614e51',
    messagingSenderId: '756530453252',
    projectId: 'hydra-bin',
    storageBucket: 'hydra-bin.firebasestorage.app',
    iosBundleId: 'com.hydrabin.hydra_host',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn756TUdxyRR7Gfo7bjqT-gtrU7hfyO9E',
    appId: '1:756530453252:macos:4d48150ce03e4e6e614e51',
    messagingSenderId: '756530453252',
    projectId: 'hydra-bin',
    storageBucket: 'hydra-bin.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn756TUdxyRR7Gfo7bjqT-gtrU7hfyO9E',
    appId: '1:756530453252:windows:4d48150ce03e4e6e614e51',
    messagingSenderId: '756530453252',
    projectId: 'hydra-bin',
    storageBucket: 'hydra-bin.firebasestorage.app',
  );
}
